from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pmeter.runner import RunResult


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PMeter Report - {timestamp}</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
      background:#0f172a;color:#e2e8f0;min-height:100vh}}
header{{background:#1e293b;border-bottom:1px solid #334155;padding:1.5rem 2rem;
        display:flex;align-items:center;gap:1rem}}
header h1{{font-size:1.5rem;font-weight:700;color:#38bdf8}}
header .meta{{color:#94a3b8;font-size:.875rem}}
main{{padding:2rem;max-width:1400px;margin:0 auto}}
.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:1rem;margin-bottom:2rem}}
.card{{background:#1e293b;border:1px solid #334155;border-radius:.75rem;padding:1.25rem;text-align:center}}
.card .label{{color:#94a3b8;font-size:.75rem;text-transform:uppercase;letter-spacing:.05em;margin-bottom:.5rem}}
.card .value{{font-size:1.75rem;font-weight:700}}
.card .value.green{{color:#4ade80}}
.card .value.red{{color:#f87171}}
.card .value.blue{{color:#60a5fa}}
.card .value.yellow{{color:#fbbf24}}
.section{{background:#1e293b;border:1px solid #334155;border-radius:.75rem;padding:1.5rem;margin-bottom:1.5rem}}
.section h2{{font-size:1rem;font-weight:600;color:#cbd5e1;margin-bottom:1rem;
             border-bottom:1px solid #334155;padding-bottom:.75rem}}
table{{width:100%;border-collapse:collapse;font-size:.875rem}}
th{{color:#94a3b8;font-weight:500;text-align:left;padding:.625rem .75rem;
    border-bottom:1px solid #334155;white-space:nowrap}}
td{{padding:.625rem .75rem;border-bottom:1px solid #1e293b;vertical-align:top}}
tr:hover td{{background:#263148}}
.pass{{color:#4ade80;font-weight:600}}
.fail{{color:#f87171;font-weight:600}}
.err{{color:#94a3b8;font-size:.75rem;font-family:monospace;max-width:320px;
      overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
.charts{{display:grid;grid-template-columns:repeat(auto-fit,minmax(380px,1fr));gap:1.5rem;margin-bottom:1.5rem}}
canvas{{max-height:280px}}
footer{{text-align:center;color:#475569;font-size:.75rem;padding:2rem}}
</style>
</head>
<body>
<header>
  <h1>PMeter Report</h1>
  <span class="meta">{timestamp} &nbsp;|&nbsp; {scene}</span>
</header>
<main>
  <div class="cards">
    <div class="card"><div class="label">Duration</div>
      <div class="value blue">{duration}s</div></div>
    <div class="card"><div class="label">Total Requests</div>
      <div class="value blue">{total_requests}</div></div>
    <div class="card"><div class="label">Failures</div>
      <div class="value {fail_color}">{total_failures}</div></div>
    <div class="card"><div class="label">Failure Rate</div>
      <div class="value {fail_color}">{failure_rate}</div></div>
    <div class="card"><div class="label">RPS</div>
      <div class="value yellow">{rps}</div></div>
    <div class="card"><div class="label">P50</div>
      <div class="value green">{p50}ms</div></div>
    <div class="card"><div class="label">P95</div>
      <div class="value yellow">{p95}ms</div></div>
    <div class="card"><div class="label">P99</div>
      <div class="value red">{p99}ms</div></div>
  </div>

  <div class="charts">
    <div class="section">
      <h2>Response Times (ms)</h2>
      <canvas id="rtChart"></canvas>
    </div>
    <div class="section">
      <h2>Requests vs Failures</h2>
      <canvas id="rfChart"></canvas>
    </div>
  </div>

  <div class="section">
    <h2>Request Stats</h2>
    <table>
      <thead><tr>
        <th>Name</th><th>Requests</th><th>Failures</th>
        <th>Avg ms</th><th>Min ms</th><th>Max ms</th>
        <th>P50 ms</th><th>P95 ms</th><th>P99 ms</th>
        <th>Status Codes</th><th>Last Error</th>
      </tr></thead>
      <tbody>{request_rows}</tbody>
    </table>
  </div>

{checks_section}
</main>
<footer>Generated by PMeter &nbsp;|&nbsp; {timestamp}</footer>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>
<script>
const rtData = {rt_data};
const rfData = {rf_data};

const gridColor = "rgba(255,255,255,.08)";
const tickColor = "#94a3b8";
const baseOpts = {{
  responsive:true,
  plugins:{{legend:{{labels:{{color:tickColor}}}}}},
  scales:{{
    x:{{ticks:{{color:tickColor}},grid:{{color:gridColor}}}},
    y:{{ticks:{{color:tickColor}},grid:{{color:gridColor}}}}
  }}
}};

new Chart(document.getElementById("rtChart"),{{
  type:"bar",
  data:{{
    labels:rtData.labels,
    datasets:[
      {{label:"Avg",data:rtData.avg,backgroundColor:"#60a5fa88",borderColor:"#60a5fa",borderWidth:1}},
      {{label:"P50",data:rtData.p50,backgroundColor:"#4ade8088",borderColor:"#4ade80",borderWidth:1}},
      {{label:"P95",data:rtData.p95,backgroundColor:"#fbbf2488",borderColor:"#fbbf24",borderWidth:1}},
      {{label:"P99",data:rtData.p99,backgroundColor:"#f8717188",borderColor:"#f87171",borderWidth:1}},
    ]
  }},
  options:baseOpts
}});

new Chart(document.getElementById("rfChart"),{{
  type:"bar",
  data:{{
    labels:rfData.labels,
    datasets:[
      {{label:"Requests",data:rfData.requests,backgroundColor:"#60a5fa88",borderColor:"#60a5fa",borderWidth:1}},
      {{label:"Failures",data:rfData.failures,backgroundColor:"#f8717188",borderColor:"#f87171",borderWidth:1}},
    ]
  }},
  options:baseOpts
}});
</script>
</body>
</html>
"""

_CHECKS_SECTION = """\
  <div class="section">
    <h2>Checkpoints</h2>
    <table>
      <thead><tr>
        <th>Name</th><th>Passed</th><th>Failed</th><th>Pass Rate</th><th>Last Message</th>
      </tr></thead>
      <tbody>{check_rows}</tbody>
    </table>
  </div>
"""


def generate_html_report(result: "RunResult", output_path: str | Path, scene: str = "") -> Path:
    """Generate a self-contained HTML report and write it to *output_path*."""
    path = Path(output_path)
    totals = result.totals
    duration = f"{result.duration_seconds:.2f}"
    rps = f"{totals['requests'] / result.duration_seconds:.1f}" if result.duration_seconds else "0"
    failure_rate = f"{totals['failure_rate']:.2%}"
    fail_color = "red" if totals["failures"] > 0 else "green"

    # Per-request rows
    request_rows = []
    entries = sorted(result.stats, key=lambda e: e.name)
    for e in entries:
        codes = ", ".join(f"{k}:{v}" for k, v in sorted(e.status_codes.items()))
        err = e.last_error or ""
        row_class = ' class="fail-row"' if e.failures > 0 else ""
        request_rows.append(
            f"<tr{row_class}>"
            f"<td>{_esc(e.name)}</td>"
            f"<td>{e.requests}</td>"
            f'<td class="{"fail" if e.failures else ""}">{e.failures}</td>'
            f"<td>{e.avg_ms:.1f}</td>"
            f"<td>{e.min_ms if e.requests else 0:.1f}</td>"
            f"<td>{e.max_ms:.1f}</td>"
            f"<td>{e.percentile(0.50):.1f}</td>"
            f"<td>{e.percentile(0.95):.1f}</td>"
            f"<td>{e.percentile(0.99):.1f}</td>"
            f"<td>{codes}</td>"
            f'<td class="err" title="{_esc(err)}">{_esc(err[:60])}</td>'
            "</tr>"
        )

    # Chart data — use HTML-safe JSON (unicode-escape < > & to prevent script injection)
    labels = [e.name for e in entries]
    rt_data = _html_json({
        "labels": labels,
        "avg": [round(e.avg_ms, 1) for e in entries],
        "p50": [round(e.percentile(0.50), 1) for e in entries],
        "p95": [round(e.percentile(0.95), 1) for e in entries],
        "p99": [round(e.percentile(0.99), 1) for e in entries],
    })
    rf_data = _html_json({
        "labels": labels,
        "requests": [e.requests for e in entries],
        "failures": [e.failures for e in entries],
    })

    # Checkpoints section
    checks_section = ""
    checks = getattr(result, "checks", [])
    if checks:
        check_rows = []
        for c in checks:
            total = c.passes + c.failures
            rate = f"{c.passes / total:.0%}" if total else "n/a"
            check_rows.append(
                f"<tr>"
                f"<td>{_esc(c.name)}</td>"
                f'<td class="pass">{c.passes}</td>'
                f'<td class="{"fail" if c.failures else ""}">{c.failures}</td>'
                f"<td>{rate}</td>"
                f'<td class="err">{_esc(c.last_message or "")}</td>'
                "</tr>"
            )
        checks_section = _CHECKS_SECTION.format(check_rows="".join(check_rows))

    html = _HTML_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        scene=_esc(scene),
        duration=duration,
        total_requests=totals["requests"],
        total_failures=totals["failures"],
        failure_rate=failure_rate,
        fail_color=fail_color,
        rps=rps,
        p50=f"{totals['p50_ms']:.1f}",
        p95=f"{totals['p95_ms']:.1f}",
        p99=f"{totals['p99_ms']:.1f}",
        request_rows="".join(request_rows),
        checks_section=checks_section,
        rt_data=rt_data,
        rf_data=rf_data,
    )

    path.write_text(html, encoding="utf-8")
    return path


def _esc(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _html_json(obj) -> str:
    """JSON-encode *obj* with HTML-safe escaping so < > & can't break the page."""
    return (
        json.dumps(obj)
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
    )
